### Iterators and Generators:

* **Iterators:**
    * Iterators iterate the elments whenever we want.
    * Iter()
    * next


In [1]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [2]:
l = [1,2,3,4,56,6]
for i in l:
    print(i,end = " ")

1 2 3 4 56 6 

In [3]:
l_iter = iter(l)
print(next(l_iter))

1


In [5]:
print(next(l_iter))

3


In [6]:
print(next(l_iter))

4


In [7]:
print(next(l_iter))

56


In [8]:
print(next(l_iter))

6


In [9]:
print(next(l_iter))

StopIteration: 

In [10]:
s = "JNTUA University"
s_iter = iter(s)
next(s_iter)

'J'

In [16]:
next(s_iter)


'U'

#### Generator:
* Generators work in combination of iterators.
* Generators mainly used in functions.
    * Yield
    * next

In [20]:
def myfun():
    for i in range(1,10):
        yield i
myfun()

<generator object myfun at 0x000001C024915138>

In [21]:
g = iter(myfun())
next(g)

1

In [26]:
next(g)

6

### Data Analysis:

* Data --- Raw input(consisting of impurities)
* Information --- processed data
* Getting the required information by removing unwanted data is called Data Analysis
* For this DataAnalysis we will use 5 libraries:
    * Numpy -- scientific Calculations
    * Pandas -- numerical data as well as the string.Cleaning of data 
    * Scikit Learn -- Machine learning library
    * Matplotlib -- graphical representation
    * Seaborn -- advanced than the matplotlib
* Steps involved in Data Analysis:
    * gathering data
    * cleaning of the data
    * fill those null values or remove those nulls
    * Graphical representation
    * Feeding the data to the ML algorithm
    * Deploy the algorithm to the Machine
    

### Numpy :

* Numpy --- Numerical Python.
* This is used to perfrom scientific calculations and mathematical operations.
* Numpy library creates all the output in the array format
* We can perform matrix operations using this numpy library.
* The arrays gives us the high efficiency when compared to lists.
* we can create different dimensional arrays using numpy.
*  1 to 32 dimensional arrays can be created using numpy library.
* **Comparision between the numpy array and list:**
    * Array occupies very less space when compared to lists.
    * we cannot perform complex operations on lists where as in arrays we can.
    * Execution time is also very less when compared to lists.
    * vector operations can be performed using arrays.
    * Data can be created in different dimensions.



In [29]:
### installing numpy

In [30]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [35]:
### importing the numpy library:

import numpy as np


### Creating arrays:

**1-d array**  --- as same as the list

In [36]:
a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [37]:
type(a1)  ### type of the array

numpy.ndarray

In [38]:
### elements type

a1.dtype

dtype('int32')

In [39]:
a2 = np.array([1,'a',2,'b'])
a2

array(['1', 'a', '2', 'b'], dtype='<U11')

In [40]:
a3 = np.array([1+2j,2+3j])
a3

array([1.+2.j, 2.+3.j])

In [42]:
a3.dtype

dtype('complex128')

In [43]:
a = np.array([1,2,3,4],dtype = "complex")

In [44]:
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [45]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.append(a,'a')  ## adding a single element into the array

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'a'],
      dtype='<U11')

In [48]:
np.append(a,['b',10,'c']) ### adding multiple elements into the array.

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'b', '10', 'c'],
      dtype='<U11')

In [49]:
a = np.arange(1,10,2)## start value,end value and step value
a

array([1, 3, 5, 7, 9])

In [50]:
a.nbytes   ### memory occupied by the array

20

In [51]:
a.itemsize  ### memory occupied by each element


4

In [52]:
len(a)  ### Gives the total number of elements

5

In [54]:
### linear spacing: divides the range of into equal parts to get the required elements.The difference between the all 
## consequtive elements is same 

a = np.linspace(1,10,20) ### end value is inclusive
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [55]:
len(a)

20

In [57]:
## logarithmic spacing:
a = np.logspace(1,10,20)
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [58]:
### full :
np.full(10,"hello")

array(['hello', 'hello', 'hello', 'hello', 'hello', 'hello', 'hello',
       'hello', 'hello', 'hello'], dtype='<U5')

In [59]:
### zeros:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
### ones:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [62]:
### ndime ---dimension of the array
a.ndim 

1

**2-d array**:
* more 1-d arrays are called 2-d arrays
* rows and columns will be included in the 2d array

In [63]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
b.ndim

2

In [65]:
b.nbytes

32

In [66]:
b.itemsize

4

In [67]:
len(b)  ### number of rows in the array

2

In [68]:
b.shape  ## gives the number of rows and columns in the array

(2, 4)

In [69]:
b.size ### elements in the array

8

**3-d array:**
* combination of more two 2-d arrays is called 3-d array
* rows,columns as well as 2-d arrays.

In [74]:
c = np.array([[[1,2,3],[5,6,7]],[[2,4,6],[10,12,14]]])
print(c)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 2  4  6]
  [10 12 14]]]


In [75]:
c.ndim

3

In [76]:
c.itemsize

4

In [77]:
c.nbytes

48

In [78]:
c.shape

(2, 2, 3)

In [79]:
len(c)  ### number of 2-d arrays present

2

In [86]:
c.size 

12

**Multi dimensional:**

In [81]:


d = np.array([[1,2,3,4],[2,3,4,5]],ndmin = 6)
d

array([[[[[[1, 2, 3, 4],
           [2, 3, 4, 5]]]]]])

In [82]:
d.ndim

6

In [85]:
d = np.array([[1,2,3,4],[2,3,4,5]],ndmin = 2)
d

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

### Accessing the elements from the array:

**1-d array**

In [89]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
a[0]

1

In [91]:
a[-1]

10

In [92]:
a[-3:]

array([ 8,  9, 10])

In [93]:
a[:3]

array([1, 2, 3])

**2-d array**

* each row will have the index
* element will also have the index

In [95]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
b[1]

array([5, 6, 7, 8])

In [97]:
b[1,-1]  ### row index,element index

8

In [98]:
b[:,-1]

array([4, 8])

In [100]:
b[:,-2:]

array([[3, 4],
       [7, 8]])

**3-d array**

In [105]:
c

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 2,  4,  6],
        [10, 12, 14]]])

In [102]:
c[0]

array([[1, 2, 3],
       [5, 6, 7]])

In [103]:
c[0,0]

array([1, 2, 3])

In [104]:
c[0,0,-1]

3

In [106]:
c[:,-1,-2:]

array([[ 6,  7],
       [12, 14]])

**Shaping and Reshaping**

In [107]:
a.shape ## number of columns or number of elements

(10,)

In [108]:
b.shape ### number of rows and columns

(2, 4)

In [110]:
c.shape  ### number od 2-d arrays,rows and columns

(2, 2, 3)

In [117]:
### Reshaping: shape of the array will be changed depending upon the requirement.

### 1-d array to 2-d array:

###2 ,5
###5,2
###10,1
###1,10

print(a)

a1 = a.reshape(2,5)
print(a1)
print(a1.ndim)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [119]:
a2 = a.reshape(10,1)
a2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [120]:
### 1-d to 3-d array:

c1 = a.reshape(2,5,1)

In [121]:
c1

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [122]:
c1.ndim

3

In [124]:
a.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [125]:
a.reshape(-1,1,2)

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]]])

### Iterating the arrays:



In [127]:
## 1-d array:

for i in a:
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

In [129]:
### 2-d array:

for i in b:  ### holds row 
    for j in i: ### holds elements of row
        print(j,end = " ")

1 2 3 4 5 6 7 8 

In [130]:
### 3-d array:
for i in c:  ## holds the 2-d array
    for j in i: ###holds the row
        for k in j: ## holds the elements
            print(k,end = " ")

1 2 3 5 6 7 2 4 6 10 12 14 

In [131]:
### nditer():

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 5 6 7 2 4 6 10 12 14 

In [132]:
for i in np.nditer(a):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

### Joining of the arrays:

The shape of the array should be same while performing the concatenation

In [136]:
a
b = np.arange(20,30)
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [137]:
c = a.reshape(2,5)
b = b.reshape(2,5)

In [138]:
np.concatenate((c,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### Stastical and Mathematical operations on arrays:

In [140]:
b

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [141]:
np.max(b) ### maximum element

29

In [143]:
np.min(b) ## minimum element

20

In [144]:
np.sum(b) ### sum of all the elements

245

In [145]:
np.argmin(b)

0

In [146]:
np.argmax(b)

9

In [147]:
b.mean()

24.5

In [150]:
np.average(b)

24.5

In [151]:
np.var(b)

8.25

In [152]:
np.median(b)

24.5

In [153]:
np.std(b)

2.8722813232690143

In [154]:
np.min(b,1)  ### row indicated by 1

array([20, 25])

In [155]:
np.max(b,0) ## column indicated by 0

array([25, 26, 27, 28, 29])

In [157]:
np.argmin(b,1)

array([0, 0], dtype=int64)

In [159]:
np.sum(b,1)

array([110, 135])

**stacking:** --- arranging the elements
* Horizontal stacking
* Vertical Stacking

In [160]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
d = a
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
np.hstack((a,d))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [164]:
b 

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [166]:
a = a.reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [167]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5, 20, 21, 22, 23, 24],
       [ 6,  7,  8,  9, 10, 25, 26, 27, 28, 29]])

In [168]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [169]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949],
       [5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481]])

In [170]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [171]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [172]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153]])

In [173]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083]])

In [175]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [176]:
np.log2(a)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [177]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ]])

In [178]:
np.remainder(b,2)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [180]:
np.degrees(a)

array([[ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
        286.47889757],
       [343.77467708, 401.07045659, 458.3662361 , 515.66201562,
        572.95779513]])

In [181]:
np.diff(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [182]:
np.ediff1d(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [184]:
np.i0(b) ### bessel function

array([[   43558282,   115513961,   306692993,   815142122, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648, -2147483648]])

In [185]:
np.mod(a,4)

array([[1, 2, 3, 0, 1],
       [2, 3, 0, 1, 2]], dtype=int32)

In [186]:
np.power(b,2)

array([[400, 441, 484, 529, 576],
       [625, 676, 729, 784, 841]], dtype=int32)

In [187]:
np.reciprocal(a)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [188]:
np.reciprocal(a,dtype = float)

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [189]:
np.multiply(a,2)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [190]:
np.divide(a,2)

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ]])

In [191]:
np.real(a)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [192]:
np.imag(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [205]:
### Ravel and Flatten:

## ravel : when we create a copy array using ravel function,automatically the changes applied to the copy array will be replicated the original array also
## Flatten :Opposite to ravel
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [206]:
copy_a = a.ravel()
copy_a

array([1, 2, 3, 4, 5])

In [207]:
copy_a[0] = 10

In [208]:
copy_a

array([10,  2,  3,  4,  5])

In [209]:
a

array([10,  2,  3,  4,  5])

In [210]:
### flatten:

a

array([10,  2,  3,  4,  5])

In [211]:
copy_f = a.flatten()
copy_f

array([10,  2,  3,  4,  5])

In [212]:
copy_f[0] = 1
copy_f

array([1, 2, 3, 4, 5])

In [213]:
a

array([10,  2,  3,  4,  5])

### Random methods:

In [217]:
np.random.randint(100)  ## single integer element

41

In [219]:
np.random.rand()   ## in the range of 0 and 1 elements will be generated

0.9463860016823231

In [220]:
np.random.randint(200,size = (20))

array([114,  10, 168,  34, 105,  33, 132,   1, 101, 146,  11,  82,  20,
       125,  36, 105, 125,  16, 154, 118])

In [221]:
np.random.randint(200,size = (2,4))

array([[ 42, 170, 128,  16],
       [108, 100,   1,  44]])

In [222]:
np.random.randint(200,size = (4,3,2))

array([[[ 25,  86],
        [174,  18],
        [ 61,  93]],

       [[  0, 190],
        [ 92, 118],
        [131, 132]],

       [[112, 176],
        [  9,  42],
        [112,  45]],

       [[189, 121],
        [159,  96],
        [ 25,  48]]])

In [223]:
np.random.choice([1,2,3,4,5],size = (10))

array([5, 1, 5, 5, 5, 3, 4, 3, 5, 3])

In [224]:
np.random.choice([1,2,3,4,5],size = (2,5))

array([[4, 1, 1, 4, 1],
       [5, 5, 3, 1, 2]])

In [225]:
np.random.choice([1,2,3,4,5],size = (2,2,2))

array([[[5, 4],
        [3, 4]],

       [[4, 1],
        [2, 2]]])

In [230]:
np.random.shuffle(a)

In [231]:
a

array([ 5,  3,  2,  4, 10])

In [232]:
np.random.randn(10)

array([ 0.31493926,  0.87414476,  0.13012235,  0.44574904, -0.53659475,
        0.88177856,  0.66684353, -3.01133518, -0.67349486,  0.78697438])

In [237]:
np.random.normal()

-0.7072114453810191

In [239]:
np.random.binomial(10,p = [0,1],size = (3,2))

array([[ 0, 10],
       [ 0, 10],
       [ 0, 10]])

In [243]:
np.random.choice([1,2,3,4,5],p = [0.5,0.1,0.2,0.2,0],size = (2,5))

array([[1, 1, 1, 3, 4],
       [4, 4, 1, 1, 1]])

In [245]:
### Array Filtering:

a = np.array([1,2,25,30,40])
c = a > 20

In [246]:
a[c]

array([25, 30, 40])

In [247]:
d = a<20
a[d]

array([1, 2])